fix(release): Fixed so that v4 will go to prerelease channel
patternfly/react-user-feedback pull request #48
Opened 2023-05-05 15:00 UTC by dlabaj

Updated code to release v4 on the prerelease channel.

2023-05-05 15:02 UTC, wise-king-sullyman approved these changes

2023-05-05 15:04 UTC, wise-king-sullyman commented
Should this be targeting the v4 branch?

2023-05-05 15:36 UTC, dlabaj commented
@wise-king-sullyman Thanks for catching the v4 branch.

2023-05-05 15:42 UTC, wise-king-sullyman requested changes
Wait it looks like you have both a yarn.lock and package-lock in here now

2023-05-07 03:12 UTC, nicolethoen approved these changes

2023-05-08 15:22 UTC, merged